name: combustivel
description: Abastecer com Ãlcool ou Gasolina

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_masked_text: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/aog-white.png

  fonts:
    - family: Big Shoulders Display
      fonts:
        - asset: assets/fonts/BigShouldersDisplay-Light.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launch.png"